#!/usr/bin/env python3
"""Writes ../layout.conf: one MPC tab per mode, each in the look of the Clouds front panel -- plain panel colour, knobs with coloured
caps, and every name on a coloured tag. MPC draws the control names itself (white, from the engine's per-mode names
via dynamic_name), so the layout only puts the tags under them; nothing is baked twice.

    python3 skin/gen_layout.py
"""
import os

MODES = ["GRANULAR", "STRETCH", "LOOPING DELAY", "SPECTRAL", "OLIVERB", "RESONESTOR"]

# Names per mode (Granular, Stretch, Looping Delay, Spectral, Oliverb, Resonestor), from the Clouds and Parasites
# manuals; baked per tab. Same table as kNames in src/engine.cc, which feeds MPC's Q-Link display.
NAMES = {
    "position": ["POSITION", "SCRUB", "DELAY", "BUFFER", "PREDELAY", "BURST"],
    "size":     ["SIZE", "WINDOW", "LOOP SIZE", "WARP", "ROOM SIZE", "CHORD"],
    "texture":  ["TEXTURE", "FILTER", "FILTER", "QUANTIZE", "DAMPING", "DAMPING"],
    "density":  ["DENSITY", "DIFFUSION", "DIFFUSION", "REFRESH", "DECAY", "DECAY"],
    "pitch":    ["PITCH", "PITCH", "PITCH", "PITCH", "SHIMMER", "PITCH"],
    "spread":   ["SPREAD", "SPREAD", "SPREAD", "SPREAD", "DIFFUSION", "VOICES L/R"],
    "dry_wet":  ["BLEND", "BLEND", "BLEND", "BLEND", "DRY/WET", "DISTORTION"],
    "feedback": ["FEEDBACK", "FEEDBACK", "FEEDBACK", "FEEDBACK", "MOD SPEED", "HARMONICS"],
    "reverb":   ["REVERB", "REVERB", "REVERB", "REVERB", "MOD AMOUNT", "SCATTER"],
    "freeze":   ["FREEZE", "FREEZE", "FREEZE", "FREEZE", "INFINITE", "VOICE LOCK"],
    "trigger":  ["TRIGGER", "LOOP SYNC", "TAP", "GLITCH", "CLOCK", "STRIKE"],
    "reverse":  ["REVERSE"] * 6,
    "midi_pitch": ["MIDI PITCH"] * 6,
    "midi_root": ["ROOT NOTE"] * 6,
    "in_gain": ["IN GAIN"] * 6,
    "out_gain": ["OUT GAIN"] * 6,
}

# As on the module: POSITION / DENSITY raspberry, SIZE / TEXTURE teal, the rest white knobs on grey tags.
COLOUR = {"position": "raspberry", "density": "raspberry", "size": "teal", "texture": "teal", "in_gain": "raspberry"}

GRID = [["position", "size", "texture"],
        ["density", "pitch", "spread"],
        ["dry_wet", "feedback", "reverb"]]
COLS = [150, 410, 670]
ROWS = [205, 340, 475]
R = 38
RIGHT = 1010          # right column: Freeze, Reverse, Trigger, Quality
ROW4 = 600
TAG_W, TAG_H = 132, 26
TOGGLE_H = 26         # the default toggle's height (skin_assets): MPC's name label sits 4 px under it

# Q-Links: listed column by column, top to bottom (shadow_skin maps the list onto MPC's 4x4 grid that way).
# No Mode: the tabs are the modes. Out Gain takes the bottom-right slot.
QLINKS = ["position", "density", "dry_wet", "trigger",
          "size", "pitch", "feedback", "midi_pitch",
          "texture", "spread", "reverb", "midi_root",
          "freeze", "reverse", "quality", "out_gain"]
GAIN_X = 840          # in/out gain column, between the knob grid and the right column
NAME_GAP = 14         # knob edge (r) to the centre of its name
MARKER_R = 7          # the page marker knob's radius (post_build.py finds it by this)


def name(key, m, cx, cy, colour):
    """The control's name for mode m centred on cx,cy: white on a coloured tag, or plain dark lettering."""
    text = 'text cx=%d cy=%d label="%s" size=1.5 weight=700 color=%s' % (cx, cy, NAMES[key][m],
                                                                         "ffffff" if colour else "1a1919")
    if not colour:
        return [text]
    return ["art file=skin/pill_%s.png x=%d y=%d w=%d h=%d" % (colour, cx - TAG_W // 2, cy - TAG_H // 2, TAG_W, TAG_H),
            text]


def knob(key, m, cx, cy, r):
    colour = COLOUR.get(key)   # white knobs: plain dark lettering, no tag -- as PITCH and BLEND on the module
    return (name(key, m, cx, cy + r + NAME_GAP, colour) +
            ['knob cx=%d cy=%d r=%d label="" key=%s img=skin/knob_%s.png' % (cx, cy, r, key, colour or "white")])


def toggle(key, m, cx, cy, colour="grey"):
    return name(key, m, cx, cy + TOGGLE_H // 2 + 14, colour) + ['toggle cx=%d cy=%d label="" key=%s' % (cx, cy, key)]


def main():
    L = ["# Clouds (Parasites) skin. Generated by skin/gen_layout.py -- edit that, not this file.",
         "art_css=skin/clouds.css",
         # ink = MPC's own name labels: white, on the tags. ink_dim = the value text under them.
         "theme_bg=e6e6e3", "theme_panel=e6e6e3", "theme_line=b4b5b4", "theme_ink=ffffff", "theme_ink_dim=4a4b4a",
         "theme_ink_faint=b4b5b4", "theme_accent=c83d58", "theme_accent_hi=c83d58", "theme_knob_face=e9e9e6",
         "theme_knob_ring=d7d8d6", "theme_knob_dot=1a1919", "theme_lcd=ffffff", "theme_seg_active=009797",
         "theme_seg_inactive=f4f4f2", "theme_seg_active_tx=ffffff", "theme_box=ffffff", "theme_btn_bg=c83d58",
         "theme_btn_text=ffffff", "theme_btn_text_plain=ffffff",
         ""]
    for m, mode in enumerate(MODES):
        # One MPC tab per mode. Its first control is the page marker: an invisible knob on page_<m> in the top right
        # corner. MPC reads a page's knobs when the tab comes up (readouts it doesn't), and the engine switches to
        # that mode (see kParams in src/engine.cc). skin/post_build.py strips the marker's value text.
        L += ["[tab %s]" % mode,
              'knob cx=1262 cy=104 r=%d label="" key=page_%d img=skin/blank.png' % (MARKER_R, m),
              'text cx=24 cy=112 label="%s" size=2.2 weight=700 color=1a1919 align=left' % mode]
        for r, row in enumerate(GRID):
            for c, key in enumerate(row):
                L += knob(key, m, COLS[c], ROWS[r], R)
        L += toggle("freeze", m, RIGHT, ROWS[0], "raspberry")
        L += toggle("reverse", m, RIGHT, ROWS[1])
        # trigger: a raspberry key; it has no MPC-drawn name, so this mode's name is baked on a tag under it
        L.append('button cx=%d cy=%d label="" key=trigger' % (RIGHT, ROWS[2]))
        L += name("trigger", m, RIGHT, ROWS[2] + 38, "grey")
        # quality: segments with a baked tag above them
        L += ["art file=skin/pill_grey.png x=%d y=%d w=%d h=%d" % (RIGHT + 60 - TAG_W // 2, ROW4 - 55, TAG_W, TAG_H),
              'text cx=%d cy=%d label="QUALITY" size=1.5 weight=700 color=ffffff' % (RIGHT + 60, ROW4 - 42)]
        L.append('enum_h cx=%d cy=%d label="" key=quality sw=86 options="16 ST,16 MONO,8 ST,8 MONO"' % (RIGHT + 60, ROW4))
        # gain: IN GAIN (raspberry, as on the module) and OUT GAIN into the limiter
        L += knob("in_gain", m, GAIN_X, ROWS[0], 30)
        L += knob("out_gain", m, GAIN_X, ROWS[1], 30)
        # row 4: MIDI
        L += toggle("midi_pitch", m, COLS[0], ROW4)
        L += knob("midi_root", m, COLS[1], ROW4 - 6, 22)
        L.append('text cx=%d cy=%d label="MIDI in: port Clouds N" size=1.1 weight=400 color=4a4b4a case=none'
                 % (COLS[2], ROW4))
        # The page marker has to be in the tab's Q-Link set: MPC reads a page's Q-Link params when the tab comes up
        # (Q-Links follow the page), and nothing else on a tab switch. It takes MIDI Pitch's slot.
        qlinks = ["page_%d" % m if k == "midi_pitch" else k for k in QLINKS]
        L += ['qlinks "%s" = %s' % (mode, ",".join(qlinks)), ""]
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "layout.conf")
    open(path, "w").write("\n".join(L) + "\n")
    print("wrote", os.path.normpath(path))


if __name__ == "__main__":
    main()
